### ISSUE TITLE
Keep compiled wordlists separate?

### ISSUE THREAD

**Issue by 0xdevalias** [assetnote/commonspeak2#1]
While I love the idea of having premise wordlists, I wonder if keeping them in this same repo might clutter things up/make it too big.

Would it make more sense to have a separate repo (like commonspeak2-wordlists or similar) to keep those in?

**Comment by infosec-au** [comment]
@0xdevalias - I'm open to this. I also plan on making a GH pages for the wordlists generated and this makes more sense. Will migrate the data over, thanks for the suggestion.
