### ISSUE TITLE
FATA[0020] Error executing BigQuery SQL.                 Error="googleapi: Error 400: Unrecognized name: origin at [17:16], invalidQuery" Mode=Subdomains Source=httparchive

### ISSUE THREAD

**Issue by backd00r101** [assetnote/commonspeak2#5]
Hello
I get this error "FATA[0020] Error executing BigQuery SQL.                 Error="googleapi: Error 400: Unrecognized name: origin at [17:16], invalidQuery" Mode=Subdomains Source=httparchive" when commonspeak tries to fetch subdomains from httparchive specifically, how can i fix this?

Command:  ./commonspeak2 --project XXXXX --credentials XXXXX subdomains -o subdomains.txt

**Comment by infosec-au** [comment]
hey @backd00r101 - I'll work on the two issues you've raised. I've been meaning to work on this more but haven't had the time. Thanks for reporting these issues.

**Comment by arbazkiraak** [comment]
Similar issue.

**Comment by infosec-au** [comment]
Fixed in PR #8
